/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/frontend/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#57344f",
        "primary-container": "#714b67",
        "primary-fixed": "#ffd7f1",
        "primary-fixed-dim": "#e9b8d9",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#2f1029",
        "on-primary-fixed-variant": "#5f3b56",
        "on-primary-container": "#f0bfe0",
        "inverse-primary": "#e9b8d9",
        "secondary": "#13677b",
        "secondary-container": "#a1e7ff",
        "secondary-fixed": "#b2ebff",
        "secondary-fixed-dim": "#8bd1e8",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f27",
        "on-secondary-fixed-variant": "#004e5f",
        "on-secondary-container": "#18697e",
        "tertiary": "#2b4161",
        "tertiary-container": "#43587a",
        "tertiary-fixed": "#d5e3ff",
        "tertiary-fixed-dim": "#b2c7ef",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#021c3a",
        "on-tertiary-fixed-variant": "#324768",
        "on-tertiary-container": "#b9cff6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#79526f",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        "on-surface-variant": "#4e444a",
        "on-background": "#191c1e",
        "outline": "#80747a",
        "outline-variant": "#d1c3ca"
      },
      fontFamily: {
        "headline": ["Manrope", "system-ui", "sans-serif"],
        "body": ["Inter", "system-ui", "sans-serif"],
        "label": ["Inter", "system-ui", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
