export const DOMAINS = [
  "Foundation / Company / Localization",
  "Users / Roles / Security",
  "Master Data",
  "CRM",
  "Sales",
  "Purchase",
  "Inventory",
  "Manufacturing (MRP)",
  "PLM",
  "Accounting",
  "POS",
  "Website / eCommerce",
  "Projects",
  "HR",
  "Quality",
  "Documents",
  "Sign",
  "Approvals"
]
  .map((label) => ({ id: label.toLowerCase().replace(/[^a-z0-9]+/g, "-"), label }))
  .concat([
    { id: "field-service", label: "Field Service" },
    { id: "maintenance", label: "Maintenance" },
    { id: "rental", label: "Rental" },
    { id: "repairs", label: "Repairs" },
    { id: "subscriptions", label: "Subscriptions" },
    { id: "timesheets", label: "Timesheets" },
    { id: "expenses", label: "Expenses" },
    { id: "attendance", label: "Attendance" },
    { id: "recruitment", label: "Recruitment" },
    { id: "fleet", label: "Fleet" },
    { id: "events", label: "Events" },
    { id: "email-marketing", label: "Email Marketing" },
    { id: "helpdesk", label: "Helpdesk" },
    { id: "payroll", label: "Payroll" },
    { id: "planning", label: "Planning" },
    { id: "knowledge", label: "Knowledge" },
    { id: "discuss", label: "Discuss / Messaging" },
    { id: "outgoing-mail", label: "Outgoing Mail" },
    { id: "incoming-mail", label: "Incoming Mail" },
    { id: "accounting-reports", label: "Accounting Reports" },
    { id: "spreadsheet", label: "Spreadsheet" },
    { id: "live-chat", label: "Live Chat" },
    { id: "whatsapp", label: "WhatsApp" },
    { id: "sms-marketing", label: "SMS Marketing" },
    { id: "calendar", label: "Calendar" },
    { id: "iot", label: "IoT" },
    { id: "studio", label: "Studio" },
    { id: "consolidation", label: "Consolidation" },
    { id: "lunch", label: "Lunch" },
    { id: "referrals", label: "Referrals" },
    { id: "loyalty", label: "Loyalty / Gift Cards" },
    { id: "appraisals", label: "Appraisals" },
    { id: "voip", label: "VoIP" }
  ]);
