export const DOMAINS = [
  "Foundation / Company / Localization",
  "Users / Roles / Security",
  "Master Data",
  "CRM",
  "Sales",
  "Purchase",
  "Inventory",
  "Manufacturing (MRP)",
  "PLM",
  "Accounting",
  "POS",
  "Website / eCommerce",
  "Projects",
  "HR",
  "Quality",
  "Documents",
  "Sign",
  "Approvals",
  "Field Service",
  "Maintenance",
  "Rental",
  "Repairs",
  "Subscriptions",
  "Timesheets",
  "Expenses",
  "Attendance",
  "Recruitment",
  "Fleet",
  "Events",
  "Email Marketing",
  "Helpdesk",
  "Payroll",
  "Planning",
  "Knowledge"
].map((label) => ({ id: label.toLowerCase().replace(/[^a-z0-9]+/g, "-"), label }));
